### ISSUE TITLE
Import Error for patients-demographics-clinical-history 

### ISSUE THREAD

**Issue by profisysitsolutions** [sdhealthconnect/leap-fhir-seed-data#2]
While importing data of patients-demographics-clinical-history to open hapi server below error is found :

Warning!
Message body does not appear to be a valid FHIR resource instance document. Body should start with '<' (for XML encoding) or '{' (for JSON encoding).

File Location : leap-fhir-seed-data\seed-data\patients-demographics-clinical-history

Need help understanding. I am using HAPI server code from : https://github.com/sdhealthconnect/hapi-fhir-jpaserver-starter

**Comment by ddecouteau** [comment]
Please provide steps you performed to get this error

**Comment by profisysitsolutions** [comment]
1. Open HAPI Server (In my case - http://localhost:8080)
2. Click Server Home/Actions
3. Find Post a bundle containing multiple resources to the server and store all resources within a single atomic transaction.
4. Copy and Paste any JSON from leap-fhir-seed-data\seed-data\patients-demographics-clinical-history location
5. Hit Transaction Button

**Comment by mojitoj** [comment]
This looks like a resource validation issue. Check your resource content and follow HAPI's error messages. All of the resources in this repo are valid JSON and the error you have cited does not seem to apply.
You might have to modify the resources based on the HAPI version and generally debug this by checking the FHIR Specs.
